### ISSUE TITLE
Option to run without frontend

### ISSUE THREAD

**Issue by JM-Lemmi** [JM-Lemmi/ical-relay#130]
cmdline start option like `--no-frontend` to run just the ical-editing part. the `/profile` paths must still be availible.

**Comment by robske110** [comment]
Would this not be better handled by a reverse proxy rule? Or is your goal removing the hard dependency on the templates directory?

**Comment by JM-Lemmi** [comment]
Might be. But better than blocking the access there is just not having those code paths active imo.
