### ISSUE TITLE
Enhancement: Send Outlook Event invites and automatically update & cancel them

### ISSUE THREAD

**Issue by DeveloperMarius** [JM-Lemmi/ical-relay#159]
Hey,
wie ich es bei @JM-Lemmi schon einmal angesprochen habe, wäre eine Funktion sinnvoll, bei welcher die Vorlesungen via Outlook invites an eine E-Mail gesendet wird.

Wieso?
Für die Arbeit ist es sinnvoll den DHBW Kalendar nicht nur via ical zur Verfügung zur stellen, sondern auch als normale Termine, welche wirklich vollständig in den Kalendar integriert werden können. Immer mehr Unternehmen arbeiten mit dem Terminplanungs Assistenten oder stellen Kunden direkt bookwithme links zur Verfügung, über welche diese direkt Termine buchen können. Diese Funktionen funktionieren jedoch nicht mit integrierten ical Kalendern. Auch Mitarbeiter einfach in einem anderen Kalender sie Verfügbarkeit einsehen können ist ein weiterer usecase.

Wie?
Ich habe raus gehört, dass Ihr einen Cache pflegt. Also könnte man in die bereits existierenden update, add und delete funktionen einfach für eine art newsletter diese emails einpflegen.

Probleme?
1. E-Mails automatisch annehmen?
Man könnte einen kleinen Snippet schreiben, welcher E-Mails von euch automatisch annimmt.
Bsp: https://www.slipstick.com/outlook/calendar/autoaccept-a-meeting-request-using-rules/
2. Spam Erkennung von MS
Am besten würde man besonders zu Semesterbeginn nicht direkt alle Emails auf einmal senden, weil Ihr sonst als Spam Sender eingestuft werden könntet. Der Einsatz eines simplen Schedulers wäre also hier sinnvoll, welcher nur eine Gewisse Anzahl an E-Mails pro Minute sendet. Hierbei spreche ich nicht vom Spam Ordner, sondern das ihr direkt von MS auf eine Blacklist kommt.

Ich freue mich auf euer Feedback.

~ Marius

**Comment by JM-Lemmi** [comment]
Duplicate of #43

But a very nice detailed explanation. Can you comment over there?
