### ISSUE TITLE
Allow empty strings in `edit` action

### ISSUE THREAD

**Issue by frereit** [JM-Lemmi/ical-relay#200]
Currently, if any property is explicitly empty (i.e `new-location: ""`) it is treated the same as non-existent keys:

https://github.com/JM-Lemmi/ical-relay/blob/fe4da1fcef05e347bd37358a0fc4490fd5cfc2d3/pkg/modules/actions.go#L95

**Comment by JM-Lemmi** [comment]
Thats a Problem in GO. I don't think you can differentiate between an empty and non-existent element in a dict.
