### ISSUE TITLE
Escape newline in description

### ISSUE THREAD

**Issue by HOOK-Hawkins** [JM-Lemmi/ical-relay#202]
Adding a Description with newline doesn't properly escape the newline leading to a malformed calendar.

```
debian@j-bwc-cal:/etc/ical-relay/calstore$ cat TINF21CS1-past.ics | grep -A 5 -B 5 "Raum A"
UID:20231127T123000Z-374534001@group-e.dhbw-mannheim.de
DTSTAMP:20231113T124108Z
SUMMARY:KAuMA Labor
DTSTART;TZID=Europe/Berlin:20231127T133000
DTEND;TZID=Europe/Berlin:20231127T163000
LOCATION:Raum A: https://bbb.dhbw.de/mannheim/bau-ryz-992-80g Raum B:
  https://bbb.dhbw.de/mannheim/bau-8ci-58y-ad3
DESCRIPTION:Raum A: https://bbb.dhbw.de/mannheim/bau-ryz-992-80g
Raum B:
  https://bbb.dhbw.de/mannheim/bau-8ci-58y-ad3
END:VEVENT
BEGIN:VEVENT
UID:20231128T083000Z-374547001@group-e.dhbw-mannheim.de
```

**Comment by HOOK-Hawkins** [comment]
When inserting a new line into the description field when editing an entry, something cant handle it an throws an error: "Error loading history file: malformed calendar; expected end"

**Comment by frereit** [comment]
This is an issue in `golang-ical`. It is that modules responsibility to escape the values when saving them into an ICAL. We should investigate where this happens and fix it. Investigating...
