### ISSUE TITLE
Token-Administration

### ISSUE THREAD

**Issue by JM-Lemmi** [JM-Lemmi/ical-relay#214]
unter `/admin` tritt folgender Fehler auf mit einem gültigen Supertoken

![image](https://github.com/JM-Lemmi/ical-relay/assets/41118534/a8f40343-7f52-47a2-ae41-96f37597057c)

![image](https://github.com/JM-Lemmi/ical-relay/assets/41118534/78e22cb1-7913-4b59-878a-7015283b4f54)

Es scheint mir ein Zusammensetzungsfehler zu sein, mit dem doppelten slash.

**Comment by nilsfast** [comment]
Gefixt durch #203?

**Comment by JM-Lemmi** [comment]
Jup, da war ich zu voreilig mit dem Issue erstellen.
