### ISSUE TITLE
Interpreting Events without Timezone leads to incorrect times in frontend

### ISSUE THREAD

**Issue by frereit** [JM-Lemmi/ical-relay#65]
Events without timezones are interpreted as UTC by default. They should be interpreted maybe as the server timezone?

This should be done in the backend.

![grafik](https://user-images.githubusercontent.com/18506129/203080271-e099da0a-9ee5-472f-81c3-eb7492c99fbf.png)
![grafik](https://user-images.githubusercontent.com/18506129/203080301-da4a99d6-017c-4055-b429-8ae6768173cc.png)

**Comment by JM-Lemmi** [comment]
I bet this log is related. I do remember writing it 😅

```
time="2022-11-29T21:59:54+01:00" level=debug msg="Unknown component type ignored: *ics.VTimezone\n"
```

**Comment by frereit** [comment]
>  They should be interpreted maybe as the server timezone?

This is already happening. The server timezone was just set incorrectly.

**Comment by frereit** [comment]
Reopening. The underlying issue, that we're not parsing the VTIMEZONE block, still persists. Server timezone is just a fallback for now.

**Comment by JM-Lemmi** [comment]
This is an issue with `VTIMEZONE` Block, that should be handled in the upstream library
