### ISSUE TITLE
Add new event by drag&drop'ing an ICS file

### ISSUE THREAD

**Issue by JM-Lemmi** [JM-Lemmi/ical-relay#68]
Outlook seems to generate a single Event ICS file when dragging an Event to a webpage. Using that to add an event to the calendar would be great!

Edit:
Outlook seems to drop an OLE2 document. Instead, this issue is now about drag&drop'ing a raw ICS file.

**Comment by frereit** [comment]
Drag-and-dropping an outlook event seems to give some kind of office document:

```
File type:   Microsoft Office document/OLE2
Extension:   ole2,doc,xls,dot,ppt,xla,ppa,pps,pot,msi,sdw,db,vsd,msg
MIME type:   application/msword,application/vnd.ms-excel,application/vnd.ms-powerpoint
Description: Microsoft Office documents
```

This seems difficult to parse, do we really want to do this?

**Comment by JM-Lemmi** [comment]
If we drag an ics file into the window is that better? Then maybe this issue needs to be split in two.

The OLE2 parsing should be moved to backlog.
