### ISSUE TITLE
Transition to Database Storage

### ISSUE THREAD

**Issue by JM-Lemmi** [JM-Lemmi/ical-relay#84]

**Comment by JM-Lemmi** [comment]
Für compatibility würde ich mir wünschen, dass man weiterhin eine yaml importieren kann beim start. zB weiterhin mit dem `--config` parameter.

Ein yaml export wird dann wahrscheinlich schwer.

**Comment by JM-Lemmi** [comment]
> Ich würde präferieren, wenn das integriert bleibt in einer binary und die DB als Datei abliegt, zB mit SQlite

**Comment by JM-Lemmi** [comment]
I think GORM would be a great idea to use. The backend can then be Postgres or SQLite. Might even make it easier to store the calendar objects in the DB?

https://gorm.io/

**Comment by JM-Lemmi** [comment]
- [ ] deprecate reload api

https://github.com/JM-Lemmi/ical-relay/blob/c3a0e9ce4f0b946ad5b93ac0f5ae620c980cd74c/api.go#L42-L56

**Comment by robske110** [comment]
Reload API is currently used on dev to trigger a re-import of a config. (See https://github.com/robske110/ical-relay/blob/dev_vlplan_live/config.go#L164)
If this should actually be supported, is debatable, but I wanted to mention it.

Apart from all this, the reload API should definitively be restricted to super admins, if it prevails.

**Comment by JM-Lemmi** [comment]
In my opinion this is not needed. This was my workaround for changing the config on the fly then firing a curl to reload it. This would better be handled by a `systemctl reload` or similar, if at all needed.
