### ISSUE TITLE
Superadmin Interface to add/generate new Tokens

### ISSUE THREAD

**Issue by JM-Lemmi** [JM-Lemmi/ical-relay#91]

**Comment by JM-Lemmi** [comment]
Tokens könnte einfach per Mail direkt versendet werden, dann müsste der Superadmin das gar nicht sehen

**Comment by robske110** [comment]
Frontend html mockup:
<img width="1329" alt="image" src="https://user-images.githubusercontent.com/16020100/218328968-3160a515-1036-41a5-8010-1bb34344f86e.png">

**Comment by JM-Lemmi** [comment]
Wenn die Reihenfolge nondeterministisch ist, würde ich vorne die Nummernspalte einfach weglassen

**Comment by JM-Lemmi** [comment]
Depends on #84
