### ISSUE TITLE
Events are all displaced by +1h

### ISSUE THREAD

**Issue by Stahrick** [JM-Lemmi/ical-relay#96]
Your Version:
![image](https://user-images.githubusercontent.com/16214265/206480198-a8e468d0-01e7-4659-8d8b-ac7e520d1d9b.png)
DHBW Version:
![image](https://user-images.githubusercontent.com/16214265/206480423-83d02043-0154-4b6d-bea4-adbe1d9f167e.png)

Course: TINF21CS1
Is also like that for other courses

Version: 2.0.0-beta.3.1

**Comment by Stahrick** [comment]
Tested on Brave and Edge

**Comment by frereit** [comment]
Duplicate of #65
